### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 221V** [altenwald/leprechaun#1]
nice demo game, but with bugs
https://i.imgur.com/V6FrQK4.png

anyway thank you :)

**Comment by manuel-rubio** [comment]
Sorry @221V the game is limited to 2 hours, if you are playing for more than 2 hours, the process is terminated and that's because is giving you a "GAME OVER" message. Maybe we could increase to 6 hours the limit.

**Comment by 221V** [comment]
oh.. leaders table is not so long in new version ((
maybe will be cool to make page with top 100 list ?

**Comment by manuel-rubio** [comment]
@221V feel free to suggest new features or report issues you find.
